package server

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// validVersionRegex matches version strings of the form X.Y or X.Y.Z where X, Y, Z are integers.
// This is used to sanitize user-supplied version strings and prevent path traversal attacks.
var validVersionRegex = regexp.MustCompile(`^[0-9]+\.[0-9]+(\.[0-9]+)?$`)

const (
	// FirmwareMaxSize is the maximum allowed firmware file size (3MB covers merged binaries)
	FirmwareMaxSize = 3 * 1024 * 1024
	// FirmwareMinSize is the minimum allowed firmware file size (200KB)
	FirmwareMinSize = 200 * 1024

	// partitionTableOffset is the flash offset of the ESP32 partition table.
	// The compiled partition table always starts with magic bytes 0xAA 0x50 at this address.
	partitionTableOffset = 0x8000
	// appPartitionOffset is the flash offset of the ota_0 app partition in the default
	// ESP32-C3 4MB partition table. This is where the app firmware starts in a merged binary.
	appPartitionOffset = 0x10000
)

// IsMergedBinary returns true if data is a merged firmware binary
// (bootloader + partition table + boot_app0 + app), as generated by esptool merge_bin.
// Detection: the compiled partition table always starts with magic bytes 0xAA 0x50
// at offset 0x8000 in the merged binary.
func IsMergedBinary(data []byte) bool {
	return len(data) > partitionTableOffset+1 &&
		data[partitionTableOffset] == 0xAA &&
		data[partitionTableOffset+1] == 0x50
}

// IsMerged returns true if the stored firmware binary is a merged binary.
func (fm *FirmwareManager) IsMerged() bool {
	data, err := os.ReadFile(fm.GetFirmwarePath())
	if err != nil {
		return false
	}
	return IsMergedBinary(data)
}

// GetAppFirmware returns the app-only portion of the stored firmware binary.
// For merged binaries it extracts the app from offset 0x10000 (ota_0 partition).
// For app-only binaries it returns the full file content.
// This is the data that buzzers download for OTA updates.
func (fm *FirmwareManager) GetAppFirmware() ([]byte, error) {
	data, err := os.ReadFile(fm.GetFirmwarePath())
	if err != nil {
		return nil, fmt.Errorf("failed to read firmware: %w", err)
	}
	if IsMergedBinary(data) {
		if len(data) <= appPartitionOffset {
			return nil, fmt.Errorf("merged binary too small: no app data at offset 0x10000")
		}
		return data[appPartitionOffset:], nil
	}
	return data, nil
}

// FirmwareManager handles storage and versioning of BuzzClick firmware files.
// Firmware files are stored in {dataDir}/firmware/.
type FirmwareManager struct {
	dataDir         string
	serverVersion   string // fallback reference version when no firmware binary is stored
	embeddedFS      fs.FS  // embedded filesystem containing firmware/buzzclick-latest.bin and firmware/version.txt
	embeddedVersion string // version read from embeddedFS firmware/version.txt
}

// NewFirmwareManager creates a new FirmwareManager using the given data directory
// and the server version as a fallback reference for outdated checks.
func NewFirmwareManager(dataDir, serverVersion string) *FirmwareManager {
	return &FirmwareManager{dataDir: dataDir, serverVersion: serverVersion}
}

// SetEmbeddedFS stores the embedded filesystem reference and reads the embedded firmware version.
// The version is read from firmware/version.txt within the provided FS.
func (fm *FirmwareManager) SetEmbeddedFS(embFS fs.FS) {
	fm.embeddedFS = embFS
	data, err := fs.ReadFile(embFS, "firmware/version.txt")
	if err != nil {
		return
	}
	v := strings.TrimSpace(string(data))
	if v != "" && v != "0.0.0" {
		fm.embeddedVersion = v
	}
}

// GetEmbeddedVersion returns the version of the firmware embedded in the server binary.
// Returns an empty string if no embedded firmware is available or it is a dev placeholder.
func (fm *FirmwareManager) GetEmbeddedVersion() string {
	return fm.embeddedVersion
}

// RestoreEmbedded restores the firmware embedded in the server binary to the data directory.
// It reads firmware/buzzclick-latest.bin from the embedded FS and calls SaveFirmware.
// Unlike InitFromEmbedded, it always overwrites the stored firmware regardless of version.
// Returns an error if no embedded firmware is available or the embedded FS is not set.
func (fm *FirmwareManager) RestoreEmbedded() error {
	if fm.embeddedFS == nil || fm.embeddedVersion == "" {
		return fmt.Errorf("no embedded firmware available")
	}
	binData, err := fs.ReadFile(fm.embeddedFS, "firmware/buzzclick-latest.bin")
	if err != nil {
		return fmt.Errorf("failed to read embedded firmware binary: %w", err)
	}
	return fm.SaveFirmware(binData, fm.embeddedVersion)
}

// firmwareDir returns the path to the firmware storage directory.
func (fm *FirmwareManager) firmwareDir() string {
	return filepath.Join(fm.dataDir, "firmware")
}

// GetFirmwarePath returns the path to the canonical latest firmware binary.
func (fm *FirmwareManager) GetFirmwarePath() string {
	return filepath.Join(fm.firmwareDir(), "buzzclick-latest.bin")
}


// GetInfo returns the current firmware version, filename, size and existence flag.
// It reads the version from version.txt and checks whether the corresponding .bin exists.
// When no firmware binary is stored, it falls back to the server version as reference
// (exists=false, size=0) so the UI can always display the expected firmware version.
func (fm *FirmwareManager) GetInfo() (version, filename string, size int64, exists bool) {
	dir := fm.firmwareDir()

	versionFile := filepath.Join(dir, "version.txt")
	data, err := os.ReadFile(versionFile)
	if err != nil {
		// No stored firmware - fall back to server version as reference
		if fm.serverVersion != "" {
			return fm.serverVersion, fmt.Sprintf("buzzclick-v%s.bin", fm.serverVersion), 0, false
		}
		return "", "", 0, false
	}

	version = strings.TrimSpace(string(data))
	if version == "" {
		if fm.serverVersion != "" {
			return fm.serverVersion, fmt.Sprintf("buzzclick-v%s.bin", fm.serverVersion), 0, false
		}
		return "", "", 0, false
	}

	filename = fmt.Sprintf("buzzclick-v%s.bin", version)
	latestPath := fm.GetFirmwarePath()
	info, err := os.Stat(latestPath)
	if err != nil {
		return version, filename, 0, false
	}

	return version, filename, info.Size(), true
}

// SaveFirmware saves firmware binary data with the specified version string.
// It writes the versioned binary (buzzclick-vX.Y.Z.bin), copies it to the canonical
// latest binary (buzzclick-latest.bin), and updates version.txt.
// Returns an error if the data size is outside the allowed bounds.
func (fm *FirmwareManager) SaveFirmware(data []byte, version string) error {
	size := int64(len(data))
	if size < FirmwareMinSize {
		return fmt.Errorf("firmware too small: %d bytes (minimum %d bytes)", size, FirmwareMinSize)
	}
	if size > FirmwareMaxSize {
		return fmt.Errorf("firmware too large: %d bytes (maximum %d bytes)", size, FirmwareMaxSize)
	}

	// Sanitize version string to prevent path traversal attacks.
	// If the version is not a valid semver (X.Y or X.Y.Z), fall back to "unknown".
	if !validVersionRegex.MatchString(version) {
		version = "unknown"
	}

	dir := fm.firmwareDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create firmware directory: %w", err)
	}

	// Write versioned binary
	versionedPath := filepath.Join(dir, fmt.Sprintf("buzzclick-v%s.bin", version))
	if err := os.WriteFile(versionedPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write versioned firmware: %w", err)
	}

	// Copy to latest.bin
	latestPath := fm.GetFirmwarePath()
	if err := os.WriteFile(latestPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write latest firmware: %w", err)
	}

	// Write version.txt
	versionFile := filepath.Join(dir, "version.txt")
	if err := os.WriteFile(versionFile, []byte(version), 0644); err != nil {
		return fmt.Errorf("failed to write version.txt: %w", err)
	}

	return nil
}

// IsOutdated returns true if the given bumperVersion is older than the reference firmware version.
// The reference is the stored firmware version if available, otherwise the server version.
// Returns false when bumperVersion is empty or when no reference version can be determined.
func (fm *FirmwareManager) IsOutdated(bumperVersion string) bool {
	if bumperVersion == "" {
		return false
	}

	refVersion, _, _, _ := fm.GetInfo()
	if refVersion == "" {
		return false
	}

	return compareSemver(bumperVersion, refVersion) < 0
}

// compareSemver compares two semver strings (e.g. "3.0.8" vs "3.1.0").
// Returns -1 if a < b, 0 if a == b, 1 if a > b.
// Non-numeric components are compared lexicographically.
func compareSemver(a, b string) int {
	aParts := strings.Split(a, ".")
	bParts := strings.Split(b, ".")

	maxLen := len(aParts)
	if len(bParts) > maxLen {
		maxLen = len(bParts)
	}

	for i := 0; i < maxLen; i++ {
		var aVal, bVal int

		if i < len(aParts) {
			aVal, _ = strconv.Atoi(strings.TrimSpace(aParts[i]))
		}
		if i < len(bParts) {
			bVal, _ = strconv.Atoi(strings.TrimSpace(bParts[i]))
		}

		if aVal < bVal {
			return -1
		}
		if aVal > bVal {
			return 1
		}
	}

	return 0
}

// InitFromEmbedded extracts the firmware embedded in the server binary into the data directory.
// It reads firmware/version.txt and firmware/buzzclick-latest.bin from the provided FS.
// If the embedded version is "0.0.0" (dev build placeholder), it skips extraction.
// If a firmware already exists in dataDir with the same or newer version, it also skips.
func (fm *FirmwareManager) InitFromEmbedded(embeddedFS fs.FS) error {
	// Read embedded version
	versionData, err := fs.ReadFile(embeddedFS, "firmware/version.txt")
	if err != nil {
		return nil // no embedded version file, skip
	}
	embeddedVersion := strings.TrimSpace(string(versionData))
	if embeddedVersion == "" || embeddedVersion == "0.0.0" {
		return nil // placeholder build, skip
	}

	// Read embedded firmware binary
	binData, err := fs.ReadFile(embeddedFS, "firmware/buzzclick-latest.bin")
	if err != nil {
		return nil // no embedded binary, skip
	}

	// Check if stored firmware is already same or newer version
	storedVersion, _, _, exists := fm.GetInfo()
	if exists && compareSemver(storedVersion, embeddedVersion) >= 0 {
		return nil // already up to date
	}

	// Extract embedded firmware to data directory
	dir := fm.firmwareDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create firmware directory: %w", err)
	}

	versionedPath := filepath.Join(dir, fmt.Sprintf("buzzclick-v%s.bin", embeddedVersion))
	if err := os.WriteFile(versionedPath, binData, 0644); err != nil {
		return fmt.Errorf("failed to write versioned firmware: %w", err)
	}

	latestPath := fm.GetFirmwarePath()
	if err := os.WriteFile(latestPath, binData, 0644); err != nil {
		return fmt.Errorf("failed to write latest firmware: %w", err)
	}

	versionFile := filepath.Join(dir, "version.txt")
	if err := os.WriteFile(versionFile, []byte(embeddedVersion), 0644); err != nil {
		return fmt.Errorf("failed to write version.txt: %w", err)
	}

	return nil
}
