// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package winenum

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureDeviceInformation string = "rc(Windows.Devices.Enumeration.DeviceInformation;{aba0fb95-4398-489d-8e44-e6130927011f})"

type DeviceInformation struct {
	ole.IUnknown
}

const GUIDiDeviceInformation string = "aba0fb95-4398-489d-8e44-e6130927011f"
const SignatureiDeviceInformation string = "{aba0fb95-4398-489d-8e44-e6130927011f}"

type iDeviceInformation struct {
	ole.IInspectable
}

type iDeviceInformationVtbl struct {
	ole.IInspectableVtbl

	GetId                  uintptr
	GetName                uintptr
	GetIsEnabled           uintptr
	GetIsDefault           uintptr
	GetEnclosureLocation   uintptr
	GetProperties          uintptr
	Update                 uintptr
	GetThumbnailAsync      uintptr
	GetGlyphThumbnailAsync uintptr
}

func (v *iDeviceInformation) VTable() *iDeviceInformationVtbl {
	return (*iDeviceInformationVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiDeviceInformation2 string = "f156a638-7997-48d9-a10c-269d46533f48"
const SignatureiDeviceInformation2 string = "{f156a638-7997-48d9-a10c-269d46533f48}"

type iDeviceInformation2 struct {
	ole.IInspectable
}

type iDeviceInformation2Vtbl struct {
	ole.IInspectableVtbl

	GetKind    uintptr
	GetPairing uintptr
}

func (v *iDeviceInformation2) VTable() *iDeviceInformation2Vtbl {
	return (*iDeviceInformation2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiDeviceInformationStatics string = "c17f100e-3a46-4a78-8013-769dc9b97390"
const SignatureiDeviceInformationStatics string = "{c17f100e-3a46-4a78-8013-769dc9b97390}"

type iDeviceInformationStatics struct {
	ole.IInspectable
}

type iDeviceInformationStaticsVtbl struct {
	ole.IInspectableVtbl

	DeviceInformationCreateFromIdAsync                             uintptr
	DeviceInformationCreateFromIdAsyncAdditionalProperties         uintptr
	DeviceInformationFindAllAsync                                  uintptr
	DeviceInformationFindAllAsyncDeviceClass                       uintptr
	DeviceInformationFindAllAsyncAqsFilter                         uintptr
	DeviceInformationFindAllAsyncAqsFilterAndAdditionalProperties  uintptr
	DeviceInformationCreateWatcher                                 uintptr
	DeviceInformationCreateWatcherDeviceClass                      uintptr
	DeviceInformationCreateWatcherAqsFilter                        uintptr
	DeviceInformationCreateWatcherAqsFilterAndAdditionalProperties uintptr
}

func (v *iDeviceInformationStatics) VTable() *iDeviceInformationStaticsVtbl {
	return (*iDeviceInformationStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func DeviceInformationCreateFromIdAsync(deviceId string) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Enumeration.DeviceInformation", ole.NewGUID(GUIDiDeviceInformationStatics))
	if err != nil {
		return nil, err
	}
	v := (*iDeviceInformationStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	deviceIdHStr, err := ole.NewHString(deviceId)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().DeviceInformationCreateFromIdAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(deviceIdHStr),         // in string
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
